### ISSUE TITLE
Improvements to the README

### ISSUE THREAD

**Issue by niyonx** [yohanchatelain/pytracer#9]
Hey Yohan, here are some improvements I think can be made to the README to make it easier for anyone to get started.

- [x] Add export PYTRACER_CONFIG
- [x] Mention of the .\__pytracercache\__ folder
- [x] Add a specific example of each command to run one of the tests
- [x] Mention of needing only 1 pkl file inside trace folder

**Comment by yohanchatelain** [comment]
Thanks! Could you create a PR related to this issue?

**Comment by niyonx** [comment]
Will do!
